// Generated by gencpp from file ros_flappy_sim/CameraFrame.msg
// DO NOT EDIT!


#ifndef ROS_FLAPPY_SIM_MESSAGE_CAMERAFRAME_H
#define ROS_FLAPPY_SIM_MESSAGE_CAMERAFRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_flappy_sim
{
template <class ContainerAllocator>
struct CameraFrame_
{
  typedef CameraFrame_<ContainerAllocator> Type;

  CameraFrame_()
    : header()
    , width(0)
    , height(0)
    , step(0)
    , data_length(0)
    , data()  {
    }
  CameraFrame_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , width(0)
    , height(0)
    , step(0)
    , data_length(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _header_type;
  _header_type header;

   typedef uint32_t _width_type;
  _width_type width;

   typedef uint32_t _height_type;
  _height_type height;

   typedef uint32_t _step_type;
  _step_type step;

   typedef uint32_t _data_length_type;
  _data_length_type data_length;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> const> ConstPtr;

}; // struct CameraFrame_

typedef ::ros_flappy_sim::CameraFrame_<std::allocator<void> > CameraFrame;

typedef boost::shared_ptr< ::ros_flappy_sim::CameraFrame > CameraFramePtr;
typedef boost::shared_ptr< ::ros_flappy_sim::CameraFrame const> CameraFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_flappy_sim::CameraFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_flappy_sim::CameraFrame_<ContainerAllocator1> & lhs, const ::ros_flappy_sim::CameraFrame_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.step == rhs.step &&
    lhs.data_length == rhs.data_length &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_flappy_sim::CameraFrame_<ContainerAllocator1> & lhs, const ::ros_flappy_sim::CameraFrame_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_flappy_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c052b18bb3b86a43759aefbf998d6f5b";
  }

  static const char* value(const ::ros_flappy_sim::CameraFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc052b18bb3b86a43ULL;
  static const uint64_t static_value2 = 0x759aefbf998d6f5bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_flappy_sim/CameraFrame";
  }

  static const char* value(const ::ros_flappy_sim::CameraFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string header\n"
"uint32 width\n"
"uint32 height\n"
"uint32 step\n"
"uint32 data_length\n"
"uint8[] data\n"
;
  }

  static const char* value(const ::ros_flappy_sim::CameraFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.step);
      stream.next(m.data_length);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_flappy_sim::CameraFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_flappy_sim::CameraFrame_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.header);
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    s << indent << "step: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.step);
    s << indent << "data_length: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.data_length);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_FLAPPY_SIM_MESSAGE_CAMERAFRAME_H
